FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    vim \
    wget \
    curl \
    zip \
    unzip \
    git \
    build-essential \
    software-properties-common \
    apt-transport-https \
    ca-certificates \
    gnupg \
    lsb-release \
    supervisor \
    cron \
    nginx \
    mariadb-client \
    postgresql-client \
    sqlite3

CMD ["/bin/bash"]


