version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker-LEMP/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker-LEMP/www/html:/var/www/html
    depends_on:
      - php
 
  php:
    build: ./docker-LEMP/php
    volumes:
      - ./docker-LEMP/www/html:/var/www/html
      - ./docker-LEMP/php/src:/var/www/src
    depends_on:
      - db
 
  db:
    image: mysql:latest
    ports:
      - 13306:3306
    volumes:
      - ./docker-LEMP/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    # for m1 mac
    platform: linux/x86_64
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db
