version: "3"

services:
  php:
    build:
      context: ./php
    volumes:
      - ./php/src:/var/www/html
      - ./php/html:/var/www/html/html
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./php/src:/var/www/html
      - ./php/html:/var/www/html/html
  phpmyadmin:
    build:
      context: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - /sessions
    restart: always
