name: Test Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'projects/aws_projects/experience2_flexible_monitoring/**'
  workflow_dispatch: # 手動トリガーを有効にする

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a simple test
      run: echo "Hello, World! This is a test workflow."
