name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'projects/aws_projects/experience2_flexible_monitoring/**'  # Trigger only when changes occur in this directory

jobs:
  terraform:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repository

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1  # Set up Terraform CLI in the environment

      - name: Terraform Init
        run: terraform init  # Initialize Terraform
        working-directory: projects/aws_projects/experience2_flexible_monitoring/terraform  # The directory where your Terraform configuration files are located

      - name: Terraform Apply
        run: terraform apply -auto-approve  # Apply the Terraform configuration automatically
        working-directory: projects/aws_projects/experience2_flexible_monitoring/terraform  # The directory where your Terraform configuration files are located
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Pull AWS Access Key ID from GitHub Secrets
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Pull AWS Secret Access Key from GitHub Secrets
          AWS_REGION: ${{ secrets.AWS_REGION }}  # Pull AWS region from GitHub Secrets
          TF_VAR_key_name: ${{ secrets.KEY_NAME }}  # Pass the SSH Key Name to Terraform as a variable
