name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'projects/aws_projects/experience2_flexible_monitoring/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_key_name: ${{ secrets.KEY_NAME }}
      TF_VAR_vpc_id: ${{ secrets.VPC_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Working Directory
        run: pwd

      - name: List directory contents
        run: ls -la ./  # 現在の作業ディレクトリの内容をリストアップ

      - name: Fetch Public IP and Generate vars.tf
        run: |
          chmod +x ./fetch_public_ip.sh
          ./fetch_public_ip.sh

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
