provider "aws" {
  region = var.aws_region
}

# Security Group: Creates a security group allowing SSH access from the public IP retrieved by the script.
resource "aws_security_group" "allow_ssh" {
  name        = "allow_ssh_from_public_ip"
  description = "Allow SSH inbound traffic from a specific public IP"
  vpc_id      = var.vpc_id

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.public_ip]  # Use the public IP provided by the script
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "allow_ssh_from_public_ip"
  }
}

# EC2 Instance: Launches a t2.micro EC2 instance in the Tokyo region, attaching the security group for SSH access.
resource "aws_instance" "example" {
  ami           = "ami-0c08c226b5ff7874c"
  instance_type = "t2.micro"
  key_name      = var.key_name
  security_groups = [aws_security_group.allow_ssh.name]

  tags = {
    Name = "TerraformExample"
  }
}

# Variables: Used to configure the AWS region, SSH key pair, VPC ID, and public IP.
variable "aws_region" {
  description = "The AWS region"
  type        = string
  default     = "ap-northeast-1"
}

variable "key_name" {
  description = "The name of the SSH key pair"
  type        = string
}

variable "vpc_id" {
  description = "The VPC ID where the security group will be created"
  type        = string
}

variable "public_ip" {
  description = "The public IP address with CIDR block"
  type        = string
}
